# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: atlas.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'atlas.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61tlas.proto\x12\x05\x61tlas\"M\n\x15RegisterWorkerRequest\x12\x11\n\tworker_id\x18\x01 \x01(\t\x12\x10\n\x08hostname\x18\x02 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x03 \x01(\t\"+\n\x16RegisterWorkerResponse\x12\x11\n\tworker_id\x18\x01 \x01(\t\"8\n\x10HeartbeatRequest\x12\x11\n\tworker_id\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\t\"\x13\n\x11HeartbeatResponse\"0\n\x0c\x44ispatchTask\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x0f\n\x07\x61ttempt\x18\x02 \x01(\x03\"N\n\nTaskResult\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x0f\n\x07\x61ttempt\x18\x02 \x01(\x03\x12\x0f\n\x07skipped\x18\x03 \x01(\x08\x12\r\n\x05\x65rror\x18\x04 \x01(\t\"E\n\rWorkerMessage\x12\x11\n\tworker_id\x18\x01 \x01(\t\x12!\n\x06result\x18\x02 \x01(\x0b\x32\x11.atlas.TaskResult\"6\n\rServerMessage\x12%\n\x08\x64ispatch\x18\x01 \x01(\x0b\x32\x13.atlas.DispatchTask2\xdd\x01\n\rWorkerService\x12M\n\x0eRegisterWorker\x12\x1c.atlas.RegisterWorkerRequest\x1a\x1d.atlas.RegisterWorkerResponse\x12>\n\tHeartbeat\x12\x17.atlas.HeartbeatRequest\x1a\x18.atlas.HeartbeatResponse\x12=\n\x0bTaskChannel\x12\x14.atlas.WorkerMessage\x1a\x14.atlas.ServerMessage(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'atlas_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERWORKERREQUEST']._serialized_start=22
  _globals['_REGISTERWORKERREQUEST']._serialized_end=99
  _globals['_REGISTERWORKERRESPONSE']._serialized_start=101
  _globals['_REGISTERWORKERRESPONSE']._serialized_end=144
  _globals['_HEARTBEATREQUEST']._serialized_start=146
  _globals['_HEARTBEATREQUEST']._serialized_end=202
  _globals['_HEARTBEATRESPONSE']._serialized_start=204
  _globals['_HEARTBEATRESPONSE']._serialized_end=223
  _globals['_DISPATCHTASK']._serialized_start=225
  _globals['_DISPATCHTASK']._serialized_end=273
  _globals['_TASKRESULT']._serialized_start=275
  _globals['_TASKRESULT']._serialized_end=353
  _globals['_WORKERMESSAGE']._serialized_start=355
  _globals['_WORKERMESSAGE']._serialized_end=424
  _globals['_SERVERMESSAGE']._serialized_start=426
  _globals['_SERVERMESSAGE']._serialized_end=480
  _globals['_WORKERSERVICE']._serialized_start=483
  _globals['_WORKERSERVICE']._serialized_end=704
# @@protoc_insertion_point(module_scope)
