# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from atlas.grpc_server import atlas_pb2 as atlas__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in atlas_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WorkerServiceStub:
    """WorkerService: worker <-> control plane transport (Phase 10).

    RegisterWorker and Heartbeat are worker-initiated unary calls, matching
    docs/api/grpc-api.md exactly. TaskChannel is a Phase 10 addition to that
    documented contract (not a rewrite of it) — it exists because dispatch is
    control-plane-initiated (the Dispatcher decides and pushes), and plain
    unary gRPC cannot have the server call the client unprompted. The worker
    opens TaskChannel once and keeps it open for its lifetime; the server
    pushes a DispatchTask down it whenever Dispatcher.dispatch() decides to,
    and the worker reports back a TaskResult on the same stream once
    WorkerRuntime.execute_task() (unchanged) returns.

    See plans/phase-10-grpc.md section 4.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterWorker = channel.unary_unary(
                '/atlas.WorkerService/RegisterWorker',
                request_serializer=atlas__pb2.RegisterWorkerRequest.SerializeToString,
                response_deserializer=atlas__pb2.RegisterWorkerResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/atlas.WorkerService/Heartbeat',
                request_serializer=atlas__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=atlas__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.TaskChannel = channel.stream_stream(
                '/atlas.WorkerService/TaskChannel',
                request_serializer=atlas__pb2.WorkerMessage.SerializeToString,
                response_deserializer=atlas__pb2.ServerMessage.FromString,
                _registered_method=True)


class WorkerServiceServicer:
    """WorkerService: worker <-> control plane transport (Phase 10).

    RegisterWorker and Heartbeat are worker-initiated unary calls, matching
    docs/api/grpc-api.md exactly. TaskChannel is a Phase 10 addition to that
    documented contract (not a rewrite of it) — it exists because dispatch is
    control-plane-initiated (the Dispatcher decides and pushes), and plain
    unary gRPC cannot have the server call the client unprompted. The worker
    opens TaskChannel once and keeps it open for its lifetime; the server
    pushes a DispatchTask down it whenever Dispatcher.dispatch() decides to,
    and the worker reports back a TaskResult on the same stream once
    WorkerRuntime.execute_task() (unchanged) returns.

    See plans/phase-10-grpc.md section 4.
    """

    def RegisterWorker(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TaskChannel(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterWorker,
                    request_deserializer=atlas__pb2.RegisterWorkerRequest.FromString,
                    response_serializer=atlas__pb2.RegisterWorkerResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=atlas__pb2.HeartbeatRequest.FromString,
                    response_serializer=atlas__pb2.HeartbeatResponse.SerializeToString,
            ),
            'TaskChannel': grpc.stream_stream_rpc_method_handler(
                    servicer.TaskChannel,
                    request_deserializer=atlas__pb2.WorkerMessage.FromString,
                    response_serializer=atlas__pb2.ServerMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'atlas.WorkerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('atlas.WorkerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkerService:
    """WorkerService: worker <-> control plane transport (Phase 10).

    RegisterWorker and Heartbeat are worker-initiated unary calls, matching
    docs/api/grpc-api.md exactly. TaskChannel is a Phase 10 addition to that
    documented contract (not a rewrite of it) — it exists because dispatch is
    control-plane-initiated (the Dispatcher decides and pushes), and plain
    unary gRPC cannot have the server call the client unprompted. The worker
    opens TaskChannel once and keeps it open for its lifetime; the server
    pushes a DispatchTask down it whenever Dispatcher.dispatch() decides to,
    and the worker reports back a TaskResult on the same stream once
    WorkerRuntime.execute_task() (unchanged) returns.

    See plans/phase-10-grpc.md section 4.
    """

    @staticmethod
    def RegisterWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/atlas.WorkerService/RegisterWorker',
            atlas__pb2.RegisterWorkerRequest.SerializeToString,
            atlas__pb2.RegisterWorkerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/atlas.WorkerService/Heartbeat',
            atlas__pb2.HeartbeatRequest.SerializeToString,
            atlas__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TaskChannel(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/atlas.WorkerService/TaskChannel',
            atlas__pb2.WorkerMessage.SerializeToString,
            atlas__pb2.ServerMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
